name: Deploy to GitHub Pages

on:
  # Trigger the workflow every time code is pushed to the `main` branch
  push:
    branches: [ main ]
  # Allows manual execution of this workflow from the Actions tab on GitHub
  workflow_dispatch:

# Allow this job to clone the repository and create a page deployment
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository using git
        uses: actions/checkout@v6
      - name: Install, build, and upload site
        uses: withastro/action@v6

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
